apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeFront
  namespace: flask-app-demo
spec:
  selector:
    matchLabels:
      app: storeFront
  replicas: 1
  template:
    metadata:
      labels:
        app: storeFront
    spec:
      containers:
      - name: storeFront
        image: neosam01/flaskredis:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8383